### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Xoidren** [jhead/phantom#20] opened 2019-09-11 23:05 UTC
So the server appears in LAN games on my phone, but I can't connect to it. Specifically, it gives me an "unable to connect to server" error message. Now I'm just doing this for testing purposes as I don't have an Xbox, but I'm setting this up for someone else who does.

(Edit is because I fixed my original problem)

**Comment by jhead** [comment] 2019-09-17 02:47
Hey @Xoidren, not sure if this is similar to the issues reported in #15 but could you try updating to [phantom v0.2.0](https://github.com/jhead/phantom/releases/tag/v0.2.0) and let me know if you still have the same problem?

**Comment by edgararroyo** [comment] 2019-09-17 18:32
Since I need this for XBox (Win 10 and Mobile both have adding remote server capability) I'm good.

The newer version shows the server name and version, but I can no longer see it from Win 10 under "Friends" section where LAN games show up, but then again, this is for XBox, not for Win 10 or mobile.  Or am I missing something?

**Comment by Xoidren** [comment] 2019-09-18 21:48
I updated to version 0.2.0 and I still get this. It never makes it past "starting connection handler"
![image](https://user-images.githubusercontent.com/55215561/65188421-60e4a180-da3c-11e9-9712-3da42ecc8942.png)
(ip blotted out)

**Comment by edgararroyo** [comment] 2019-09-19 20:26
> 
> 
> I updated to version 0.2.0 and I still get this. It never makes it past "starting connection handler"
> ![image](https://user-images.githubusercontent.com/55215561/65188421-60e4a180-da3c-11e9-9712-3da42ecc8942.png)
> (ip blotted out)
> @jhead

@Xoidren just curious, does your Minecraft PE (on your mobile) not have the SERVERS tab?

![Screenshot_20190919-162343](https://user-images.githubusercontent.com/832706/65278457-293c2f00-dafa-11e9-8786-9f5420358689.png)

Under SERVERS, there is ADD SERVER where you can add the remote PE server.

![Screenshot_20190919-162347](https://user-images.githubusercontent.com/832706/65278465-2d684c80-dafa-11e9-820e-048f27b2e9bb.png)

**Comment by dub24** [comment] 2019-09-22 19:00
I can see the server on my Xbox One @edgararroyo but fails to connect as @Xoidren describes originally.  Did you actually get it to connect to the server on the Xbox?

**Comment by edgararroyo** [comment] 2019-09-22 22:03
@dub24 yes, it works, and on 3 different servers on the same server, running the proxy three times.
Sounds a bit confusing, but here is a visual...

Server: (running on outside network on Server 2012 R2)
MCPE:19132
MCPE:19133
MCPE:19134

Proxy: (running on local network on RPI 3 B)
phantom -server MCPE:19132
pahntom -server MCPE:19133
phantom -server MCPE:19134

Minecraft LAN: (running on local network on XBOX One)
MCPE (name & version of 19132)
MCPE (name & version of 19133)
MCPE (name & version of 19134)

**Comment by jhead** [comment] 2019-09-22 22:33
Hey @Xoidren, those logs look fine. If it shows up on your phone, it should show up on Xbox. Connecting is a different story. Do you know what software and version the server is running? (e.g. the official Bedrock server, PocketMine, Nukkit, etc.)

**Comment by Xoidren** [comment] 2019-09-23 00:50
> Hey @Xoidren, those logs look fine. If it shows up on your phone, it should show up on Xbox. Connecting is a different story. Do you know what software and version the server is running? (e.g. the official Bedrock server, PocketMine, Nukkit, etc.)

I think it's the official Bedrock Server (I'm using HeavyNode to host it). Also, it doesn't show up anymore in my server list on android. The only time it showed up was the time that the logs got past Starting Idle Connection Handler. How do you suppose I might troubleshoot this?

**Comment by Xoidren** [comment] 2019-09-23 00:51
> I can see the server on my Xbox One @edgararroyo but fails to connect as @Xoidren describes originally.  Did you actually get it to connect to the server on the Xbox?

No, I didn't. When I had it tested on an Xbox, it never made it past Starting Idle Connection Handler, unfortunately.

**Comment by Xoidren** [comment] 2019-09-23 00:52
@edgararroyo Thanks for the tips, but I don't actually need it to connect to the Android version of Minecraft, I was just doing that for testing purposes since I didn't have an Xbox.

**Comment by edgararroyo** [comment] 2019-09-23 01:19
@jhead what @Xoidren is saying is true.  With the new verision you can't see the servers on Android/iOS/Win10 anymore.  They do show up on XBox One though.

**Comment by Xoidren** [comment] 2019-09-23 02:47
> @jhead what @Xoidren is saying is true.  With the new verision you can't see the servers on Android/iOS/Win10 anymore.  They do show up on XBox One though.

I was just able to test it on Xbox One and it did show up, so that's cool. But I just get Unable to connect to world. I tried it with another server too and it didn't work. Does anyone know of a public server that always works to test if the problem is on my end or the server's end? @edgararroyo @jhead

**Comment by jhead** [comment] 2019-09-23 14:49
@Xoidren, you can try this test server that should always be up: lax.cubed.host:19132

I’ll see if I can reproduce the problem on other devices with the Bedrock server.

I should note that it takes a couple seconds to show up and mobile doesn’t always ping immediately, sometimes you have to close the app and reopen it to get it to show up. Win10 and Xbox have never given me any trouble though.

**Comment by edgararroyo** [comment] 2019-09-23 20:34
@jhead so your Windows 10 MC sees the LAN proxies?  On both my mobile and Win 10 it stopped showing them.  Only on XBox One they show...  And I can duplicate it, if I replace the phantom-linux with version 0.12 I can see them again on mobile/win10 but with new version they go away/disappear.

**Comment by Xoidren** [comment] 2019-09-24 03:04
> lax.cubed.host:19132

The command prompt tells me that server doesn't exist for some reason.
Failed to init server: Invalid server address: lookup lax.cubed.host: no such host
@jhead

**Comment by dub24** [comment] 2019-09-24 05:33
I found another public bedrock server at 147.135.9.160:25578 to test.

The problem still remains with mine getting stuck "Unable to connect to server" on Xbox One and Windows 10.

Starting up with remote server IP: 147.135.9.160:25578
INFO: 2019/09/24 00:23:53 proxy.go:81: Binding ping server to: 0.0.0.0:19132
INFO: 2019/09/24 00:23:53 proxy.go:90: Binding proxy server to: 0.0.0.0:51104
INFO: 2019/09/24 00:23:53 proxy.go:97: Proxy server listening!
INFO: 2019/09/24 00:23:53 proxy.go:244: Starting idle connection handler
INFO: 2019/09/24 00:25:36 proxy.go:201: Opening connection to 147.135.9.160:25578 for new client 192.168.1.11:55816!
INFO: 2019/09/24 00:25:36 proxy.go:216: Opening connection to 147.135.9.160:25578

So if the only working copy we have confirmation on is Linux (Raspbian on the RPi I assume), this has to be an issue with Windows blocking or something with the compile?  Kind of makes me want to fire up my Pi too and test it out :P

**Comment by jhead** [comment] 2019-09-24 06:43
Hey @dub24 @Xoidren, sorry about that - typo'd on my phone. It should be `lax.mcbr.cubed.host:19132`.

Let's keep this thread about the "unable to connect to server," since that's what @Xoidren is reporting. For the other issue of phantom not showing up at all, see #15

I did some testing on the devices I have laying around. It's probably safe to assume that results for Linux would be identical to macOS.

| phantom | Minecraft | Server | Status |
|----------|-----------|--------|-------|
Windows 10 | Windows 10 (same PC) | PocketMine | ❌
Windows 10 | Windows 10 (same PC) | Bedrock | ❌
Windows 10 | Windows 10 (different PC) | PocketMine | ✅
Windows 10 | Windows 10 (different PC) | Bedrock | ✅
Windows 10 | Xbox One X | PocketMine | ✅
Windows 10 | Xbox One X | Bedrock | ❌
Windows 10 | iOS | PocketMine | ✅
Windows 10 | iOS | Bedrock | ❌
macOS | Xbox One X | PocketMine | ✅
macOS | Xbox One X | Bedrock | ✅
macOS | Windows 10 | PocketMine | ✅
macOS | Windows 10 | Bedrock | ✅
macOS | iOS | PocketMine | ✅
macOS | iOS | Bedrock | ✅

Clearly there are at least two issues:
- phantom on Windows 10 + the official Bedrock server
- Windows 10 + Windows 10 (same PC)

I'll see if I can identify the issues.

**Comment by jhead** [comment] 2019-10-20 02:17
Hey everyone, thanks for your patience! Could you please update to [v0.2.1](https://github.com/jhead/phantom/releases/tag/v0.2.1) and see if this problem is resolved?

**Comment by dub24** [comment] 2019-10-20 16:48
I can confirm is is working beautifully connecting to the server from a Xbox One with the proxy hosted on Windows 10.  Server is hosted remotely and running Bedrock SE 1.12 .

Thank you!!!

**Comment by bauen1** [comment] 2019-11-01 08:45
Sadly this is still an issue.
Running on Linux Debian unstable (with the actual server external and in a docker container) and phantom running on the host.
The server does show up (including correct information) in the menu but if a client (ios 13) tries to connect it fails with "Unable to connect to server".
Minecraft Pocket Edition Version (Server + Client): 1.13

**Comment by ProdigyGG** [comment] 2020-03-21 22:47
If you have minecraft on an your ios. Then you can go in the server you want to join with your ios and then join the server on xbox. That helped me. Note your device has to be connected to the same internet with your xbox

**Comment by imnotjack91** [comment] 2020-03-26 19:07
have we identified whats going on here? im attempting to setup a deployment and have 1 running but not visible to the xbox or anything else for that matter. phantom says its running and says the devices are connecting but the devices dont see anything.

**Comment by imnotjack91** [comment] 2020-03-26 20:28
does this application use TCP or UDP? i know the dedicated server itself uses UDP but i dont know if that extends to proxy software like this.

**Comment by imnotjack91** [comment] 2020-03-27 15:01
lol so turns out windows updates had rebooted the server the night before and i didnt realize it till this morning. it is working as far as this thread goes.

**Comment by JantsoP** [comment] 2020-05-03 20:14
Are you guys running official version or some custom versions?
Since I tried with NukkitX and phantom did not connect.
But with official bedrock files, it works just fine.

**Comment by jhead** [comment] 2020-08-15 18:24
I'm going to close this issue out since the remaining problems are probably more specific, like #16. Feel free to reply or open new issues if you guys are still having trouble getting it working.

**Closed by jhead** 2020-08-15 18:24 UTC
Labels: bug
