### ISSUE TITLE
CubeCraft crashes client after joining lobby

### ISSUE THREAD

**Issue by huwusky** [jhead/phantom#103] opened 2020-07-09 06:27 UTC
Title self explanatory, forgot to add ps4 tag

**Comment by joshuaxlino** [comment] 2020-07-09 13:38
Yes i have confirmed it myself, it has something to do with no console support. The best work around i found was putting all your settings on the lowest.

**Comment by huwusky** [comment] 2020-07-09 18:26
All settings such as?

**Comment by joshuaxlino** [comment] 2020-07-09 22:52
> All settings such as? Changing them doesn't affect anything for me

All graphic settings (beautiful skies, fancy graphics etc.) and render distance + anti-aliasing.

Note: you may still crash on lowest settings, in the server turn off player visibility and wear a default steve skin.

**Comment by huwusky** [comment] 2020-08-27 21:14
Huh, weird, I still have the issue though, even after doing such

**Comment by jhead** [comment] 2021-01-02 19:48
Hey @huwusky! Have you tried this again recently? I was able to join CubeCraft from an iPhone X via phantom, but unfortunately I don't have a PS4 to reproduce your setup.

I did notice that CubeCraft freezes for 10 - 15 seconds in the lobby, probably due to the amount of players idling in there, but then it picks back up and starts working. One way you can try to fix this is adding `-workers 8` to your command line. This allows phantom to handle more data in parallel, which helps with very busy servers. In my testing, this got it running super smoothly.

**Comment by jhead** [comment] 2021-01-10 20:09
Gonna close this out but let me know if the crashes continue even after using the `-workers` flag.

**Closed by jhead** 2021-01-10 20:09 UTC
Labels: device:ps4, troubleshooting
