### ISSUE TITLE
GUI 

### ISSUE THREAD

**Issue by WhatWheatleySaid** [jhead/phantom#83] opened 2020-05-21 21:16 UTC
Hey,
I wrote a really basic GUI (dont judge me please, was just an hour) in python on top of your executable for windows. (I think only windows (and maybe MAC) users may will need a GUI for that at all)

https://github.com/WhatWheatleySaid/MC-phantom-gui

feel free to use anything of that as you like

**Comment by imnotjack91** [comment] 2020-05-21 21:46
dude! nice job! quick question, what task does it elevate for?

**Comment by imnotjack91** [comment] 2020-05-21 21:51
also, is it able to remember the servers so i can start it up with windows without having to add the servers each time?

**Comment by imnotjack91** [comment] 2020-05-21 21:52
and is it running multiple proxies at once from one window?

**Comment by WhatWheatleySaid** [comment] 2020-05-21 21:56
I'm not quite sure what your first question is asking for but I'll give it a try:
I'm just directly starting the executable as a subprocess for each server added if thats your question

For the second point :

I had that already in my mind and its probably not too hard to add, but i was lazy..
Windows has wierd permission Management, which forces me to store a possible serverlist inside specific folders. I'll have to look up again where to store the list, then its just a basic "save list on close" and "look if list exists" on startup

**Comment by imnotjack91** [comment] 2020-05-21 21:58
beautiful! these  2 projects = a match made in the aether mod

**Comment by imnotjack91** [comment] 2020-05-21 21:58
#restinpeaceaethermod

**Comment by imnotjack91** [comment] 2020-05-21 22:06
idk if its possible but how hard would it be to make aconnecteded status indicator and connect/disconnect button by each server in the list that way the user can see if the address was put in right or they got the right port number. 
i know. thats probably a lot but its real questions that if i knew how, i would be trying to put in it.
also, is it possible to add a feature to automatically open the port for the listening port number..... maybe per server?
idk i have a lot of ideas. let me know if i just need to shut up and stop lol :)

**Comment by imnotjack91** [comment] 2020-05-21 22:11
btw. in case you havent noticed im SUPER appreciative of the effort youve put in so far. im just brainstorming. please dont take it as ungreatfulness :) THANK YOU!!!!

**Comment by WhatWheatleySaid** [comment] 2020-05-21 22:32
Well, since im just spawning processes of the already compiled executionable of this repo, I have little to no control over the actual networking. I'm currently relying on the output of the Phantom.exe to catch any errors occuring, just by searching for the keyword "failed" haha.

Btw: I just added the serverlist thingy, when you close it now, it should produce a "serverlist.pckl" file and automatically start every server inside there on startup

**Comment by imnotjack91** [comment] 2020-05-22 00:53
NICE!! bro. you da man! just like Jhead

**Comment by imnotjack91** [comment] 2020-05-22 13:10
im curious if you can search for the keyword in phantom for successfull connection and display a connected status if its true and if it doesnt find the keyword for "connected" then trigger a "searching" or "connecting" indicator and upon "failed" or "stopped" keyword or status display the "not connected" status and it could just be like higlighting or a backround color or and actual label or an overlay.

i will say i lover that even though you have it formatted to recommend the ip address. i like that you can still use fqdn. makes my life much easier
f

**Comment by WhatWheatleySaid** [comment] 2020-05-22 14:24
Well, the output of Phantom is rather sparse. There seems to be no information about any connection status or similiar (except that a client has been found)

**Comment by imnotjack91** [comment] 2020-05-22 14:27
@jhead are you abel to customize the program output messages to make this possible?

**Comment by WhatWheatleySaid** [comment] 2020-05-22 14:45
@imnotjack91 in debug mode, there is actually output of the recieved pongs, if the server is indeed responding. So i may use that to atleast check if the server is reached, even if its a really errorprone and suboptimal way to do so

**Comment by imnotjack91** [comment] 2020-05-22 15:24
maybe make a branch of the project that supports additional output for gui programming to track status of?

**Comment by WhatWheatleySaid** [comment] 2020-05-22 17:04
@imnotjack91 Its now showing a connectivity status next to each server

**Comment by subsaga** [comment] 2020-05-24 13:27
i saw this after i created issue #86. I cant actually get this to run, get the attached error.
![image](https://user-images.githubusercontent.com/8171487/82755329-b68efc00-9dca-11ea-8aad-e2bcb3a2d197.png)
Windows 10 x64

**Comment by jhead** [comment] 2020-05-25 06:17
Hey @WhatWheatleySaid 👋  if you're interested, I just pushed a branch that adds an `-api` flag to phantom to enable a JSON REST API and HTTP server: #87 

You can find the endpoints here: https://github.com/jhead/phantom/blob/feature/api/internal/services/api/api.go#L46

I figure an API is better than trying to parse the console 😄

**Comment by WhatWheatleySaid** [comment] 2020-05-25 20:19
@jhead Indeed, it is! Although it was interesting to do so, I added a new version using the provided API

**Comment by imnotjack91** [comment] 2020-05-26 20:42
NICE! im going to try it tonight!

**Comment by imnotjack91** [comment] 2020-06-24 15:42
ok, so after a while of fiddling with it, i found that it does broadcast both servers im testing addresses for, however, its alternating the results. so it keeps pinging back and forth, tested on androind version, ios version, and xbox one x version. it only shows 1 server slot and alternates the server displayed every few seconds. vs when i manually run a dedicated non gui config, it shows up each to its own locally found server. was this by design? also, im not seeing the online status indicator.

**Comment by WhatWheatleySaid** [comment] 2020-06-24 15:47
@imnotjack91 currently, the Binary Release for windows is not using the API, because something seems off in the api (multiple servers don't work right now)

In the binary Release there is a GUI.exe + a Phantom Release, which in combination should work

**Comment by imnotjack91** [comment] 2020-06-24 15:53
ok. i will try reconfiguring and see if that works.

**Comment by imnotjack91** [comment] 2020-06-24 15:56
for clarity, should i download the phantom release from here and download the gui from your project to avoid the api implementation and its bugs?

**Comment by WhatWheatleySaid** [comment] 2020-06-24 15:57
@imnotjack91 no, in the Release-Tab of the GUI, there is a zip containing "GUI.exe" and a Phantom exe. Use these

**Comment by imnotjack91** [comment] 2020-06-24 16:02
ok, so i cant find a zip file on your project site. just the gui.exe and the copy of the api version of phantom. no zips that i can see.

**Comment by imnotjack91** [comment] 2020-06-24 16:10
i think i found it. under code>scroll down to 'usage'>click the download link there that gave me a zip. but i cant see a "releases" tab.

**Comment by jhead** [comment] 2021-01-10 19:55
Gonna close this issue out but nice work! I'll collect some links to these community projects and put them in the readme soon.

**Closed by jhead** 2021-01-10 19:55 UTC
