### ISSUE TITLE
Not working from Windows 7

### ISSUE THREAD

**Issue by ryanjohn1** [jhead/phantom#23] opened 2019-09-22 11:15 UTC
I'm trying to run phantom on my old Windows 7 laptop to allow my Xbox one Minecraft to connect to a remote server hosted at Aternos : https://aternos.org/server/
![phantom](https://user-images.githubusercontent.com/6177486/65386349-67239800-dd32-11e9-865a-53a5f7124d22.JPG)
Attached the output from the command prompt which looks ok as far as I can tell? But I don't see anything within the Minecraft app on Xbox, there is nothing in the friends section and my servers section just shows the 5 featured servers.
Should it be working on Windows 7?

**Comment by ryanjohn1** [comment] 2019-09-22 11:19
Also, I turned off my Windows firewall temporarily and that didn't make a difference

**Comment by jhead** [comment] 2019-09-22 22:45
Hey @ryanjohn1, thanks for the report. Do you know what Minecraft server software you're using on Aternos? e.g. the official Bedrock server, PocketMine, Nukkit, etc.

**Comment by jhead** [comment] 2019-10-19 18:11
I believe this is another duplicate of https://github.com/jhead/phantom/issues/20#issuecomment-534415209 related to phantom not working with Bedrock (non-PocketMine) servers on Windows.

**Closed by jhead** 2019-10-19 18:11 UTC
Labels: troubleshooting

**Comment by jhead** [comment] 2019-10-20 17:33
Hey @ryanjohn1, could you please try [version 0.2.1](https://github.com/jhead/phantom/releases/tag/v0.2.1) and see if this problem is resolved?
